### ISSUE TITLE
SigTest() error

### ISSUE THREAD

**Issue by dlemas** [MG-RAST/matR#55]
I started working with the sigtest() function in matR and run into an error in both the demo and while working with the demo data. An example of the code and error is below: 

Code:
groups(Guts) <- c(1,1,1,2,2,2,2)
res <- sigtest(Guts, view = "nrm", test = "t-test-un-paired")

Error:
Error in is.factor(x) : 
  promise already under evaluation: recursive default argument reference or earlier problems?

I am hoping to get some feedback or a work around as this is a very cool package with a lot of potential.

**Comment by wltrimbl** [comment]
I don't think the sigtest function is still part of the package; sorry we didn't look into this bug in time.
