### ISSUE TITLE
matR install

### ISSUE THREAD

**Issue by ewilbanks** [MG-RAST/matR#59]
Hi folks,

I'm getting an error trying to install matR - any ideas what could be going wrong here?

> library(devtools)
> install_github("MG-RAST/matR")
> Loading required package: RCurl
> Loading required package: bitops
> Installing MG-RAST/matR from hadley
> Error in file(con, "wb") : cannot open the connection
> In addition: Warning message:
> In file(con, "wb") :
>   cannot open file '/var/folders/wr/wrn6m46YGIqIPvJJXoCGME+++TM/-Tmp-//Rtmp9yBKvp/hadley-MG-RAST/matR.zip': No such file or directory

Thanks,
Lizzy

**Comment by wltrimbl** [comment]
The dependencies and install procedure have changed since this issue came up; it is unlikely the same problem persists.
