### ISSUE TITLE
cannot open: HTTP status was '401 Authorization Required'

### ISSUE THREAD

**Issue by pbajaj** [MG-RAST/matR#70]
Hi,

m facing the below mentioned problem inspite setting the key through msession$setAuth()

Warning in file(con, "r") :  
  cannot open: HTTP status was '401 Authorization Required'  
Error in fromJSON(x, asText = TRUE, simplify = TRUE) :  
  error in evaluating the argument 'content' in selecting a method for function 'fromJSON': Error in file(con, "r") : cannot open the connection

Thanks
pb

**Comment by wltrimbl** [comment]
This was most likely an expired key--the API now generates this error for out-of-date keys.
