### ISSUE TITLE
Cannot open connection: HTTP status was '0 (null)'

### ISSUE THREAD

**Issue by koenvandenberge** [MG-RAST/matR#74]
Hi,

I wrote an R script that downloads and process data from a project on the MG-Rast website using the `biomRequest` function. I used it multiple times in the past, however since yesterday the `biomRequest` function first gives me 50 or so warnings saying
`Warning: MGRASTer: resource is missing component(s): data`
and in the end gives me this:
`Warning in file(con, "r") :
  cannot open URL 'http://api.metagenomics.anl.gov/1/status/55671327-6f2d-4062-beb7-7d566773f6b9': HTTP status was '0 (null)'
Error in file(con, "r") : cannot open the connection` 

The script has been unchanged and hence it should work. Do you have an idea of the problem, or is MG-Rast's server possibly down?

Best
Koen

**Comment by DrOppenheimer** [comment]
I'd suggest contacting MG-RAST support.
http://metagenomics.anl.gov/metagenomics.cgi?page=Contact

**Comment by wltrimbl** [comment]
This seems to have been a temporary outage.
