### ISSUE TITLE
Getting count data but no row/column names

### ISSUE THREAD

**Issue by johnsra3** [MG-RAST/matR#75]
I'm using code for matR that has previously worked to pull down data with the KEGG and SEED functional groups from MG-RAST. However, when I use this code now, I either get counts data with no column and row names, or I get the following error: 
Error in `rownames<-`..... Length of 'dimnames' [1] not equal to array extent

I've contacted MG-RAST in the past when their servers were down, but it appears from their website that the servers are back up and that the data is loaded onto the site.

**Comment by wltrimbl** [comment]
Can you provide a minimal reproducible example of the request that gives you this error?
