### ISSUE TITLE
matR being maintained?

### ISSUE THREAD

**Issue by lstanish** [MG-RAST/matR#77]
Hi,
The most recent version of matR (1.0) doesn't appear on Cran (v0.9). Is it still being maintained? Also, is matR still being maintained?
Thanks.

**Comment by wltrimbl** [comment]
Yes.  (Our most recent maintenance patches are form March 2017).   Some time soon we will prepare an update to CRAN; in the meanwhile you need to get the development versions of matR and MGRASTer from github.  

If you have problems accessing your data or using the R client, let us know (here or at the MG-RAST help desk) and we'll do our best to get your data out of the machine.
