### ISSUE TITLE
Error in QUICK START

### ISSUE THREAD

**Issue by haruosuz** [MG-RAST/matR#79]
Following QUICK START https://github.com/MG-RAST/matR
I got Error as follows:

	> library(matR)
	Loading required package: MGRASTer
	MGRASTer (0.9 02e288)
	Loading required package: BIOM.utils
	BIOM.utils (0.9 dbcb27)
	matR: metagenomics analysis tools for R (0.9 c71ee9)
	Suggested package(s) missing: value

	> list_mgp80869 <- metadata("mgp80869")$mgp80869

	> biom_phylym <- biomRequest(list_mgp80869, request="organism", hit_type="all", source="RDP", group_level="phylum", evalue=15,  wait=TRUE)
	Error in file(con, "r") : cannot open the connection

My environment is as follows:

	> sessionInfo()
	R version 3.3.3 (2017-03-06)
	Platform: x86_64-apple-darwin13.4.0 (64-bit)
	Running under: OS X Mavericks 10.9.5
	
	locale:
	[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
	
	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     
	
	other attached packages:
	[1] RJSONIO_1.3-0  matR_0.9       BIOM.utils_0.9 MGRASTer_0.9  
	
	loaded via a namespace (and not attached):
	[1] tools_3.3.3

Regarding http://www.mcs.anl.gov/~braithwaite/library/matR/doc/matR-user-manual.pdf
http://dunkirk.mcs.anl.gov/~braithwaite
the URL is broken.

**Comment by wltrimbl** [comment]
Two suggestions:
Your versions of matR and MGRASTer (from CRAN) are out of date, and are missing some bug fixes.   You can update your packages with 

    remove.packages('MGRASTer')
    remove.packages('matR')
    install.packages('devtools')
    library(devtools)
    install_github(repo='MG-RAST/MGRASTer')
    install_github(repo='MG-RAST/matR')
    quit()

Secondly, the API call takes a Really Long Time.  Making a second attempt (after two hours have passed, but before four days have passed) makes it less likely to time out, since the server will cache the result of a long-running database query and have it ready.

This is the expected output:

    > biom_phylum <- biomRequest(list_mgp80869, request="organism", hit_type="all", source="RDP", group_level="phylum", evalue=15,  wait=TRUE, quiet=FALSE)
    start stop requested                               ticket
    1     1   50      TRUE 5c88bbda-c785-48b7-b9bb-47f3ba9be9f8
                                                                          file
    1 /var/folders/2g/k5ylcjt57_d4bqw352_flw740000gn/T//Rtmp8EzRPE/file6a378aee4f9
    > biom_phylum
                                                   mgm4750361.3 mgm4750362.3 mgm4750363.3 mgm4750364.3    mgm4750365.3
    unclassified (derived from Bacteria)                        624         1032          454          679          707
    Actinobacteria                                              830          477          594          662          602
    Proteobacteria                                              392          540          246          353          306
    ...

If the update + retry don't resolve your issue, let us know.

**Comment by haruosuz** [comment]
Thank you. The problem was solved when I updated the MGRASTer package from ‘0.9’ to ‘0.9.1’.
https://github.com/MG-RAST/matR#quick-start
`biom_phylym <-`
should be 
`biom_phylum <-`
